language: python
python:
  - "2.7"

install: pip install -r _modules_tests/requirements.txt

before_script: export PYTHONPATH=$(pwd)/_modules/:$(pwd)/_modules_tests/unit/:$PYTHONPATH
script: python -m unittest discover -s _modules_tests/unit -p "*.py"
